[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.lesson4.model.Post[]" --]
[#-- @ftlvariable name="post" type="ru.itmo.web.lesson4.model.Post" --]
[#-- @ftlvariable name="requestPath" type="String" --]
